## Deliverable Two. 

### Cleaning and Preparing the Dunkin' Donuts Menu for Analysis.

**Task 2.1:**

Repeat the same steps as Task 1.1, except import the BUS_303_Dunkin_Donuts_Nutritional_Menu_Kaggle_2023.csv file.

In [1]:
# Task 2.1: Import pandas as pd to work with a package that can process dataframes.
# ENTER CODE BELOW THIS LINE.
import pandas as pd

# Import the BUS_303_Dunkin_Donuts_Nutritional_Menu_Kaggle_2023.csv file using the pandas package.
# Assign the file object name dnkn.
# ENTER CODE BELOW THIS LINE.
dnkn = pd.read_csv('BUS_303_Dunkin_Donuts_Nutritional_Menu_Kaggle_2023.csv')

**Task 2.2:**

- Examine the Dataset Structure

- Business analysts must first understand the structure of a dataset before making any modifications.

After reviewing the output:

- Which variables appear to be numerical?
- Which variables appear to be categorical?
- Are there any columns that appear to have an incorrect data type?

In [3]:
# Task 2.2: Examine the Dataset Structure

# ENTER CODE BELOW THIS LINE.
dnkn.info()
dnkn.head()

<class 'pandas.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Category             780 non-null    str
 1   Item                 780 non-null    str
 2   Calories             780 non-null    str
 3   Total Fat (g)        780 non-null    str
 4   Saturated Fat (g)    780 non-null    str
 5   Trans Fat (g)        780 non-null    str
 6   Cholesterol (mg)     780 non-null    str
 7   Sodium (mg)          780 non-null    str
 8   Carbs (g)            780 non-null    str
 9   Fiber (g)            780 non-null    str
 10  Sugars (g)           780 non-null    str
 11  Protein (g)          780 non-null    str
 12  Weight Watcher Pnts  780 non-null    str
dtypes: str(13)
memory usage: 132.8 KB

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0,0,0,0,20,0,0,0,1,4
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0,0,0,0,15,0,0,0,0,5
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0,0,0,0,10,0,0,0,0,5
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12,6,0,35,65,2,0,2,2,126
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9,4.5,0,25,45,1,0,1,2,93.5

**Task 2.3:**

- Explore Missing Values

- Missing values can negatively affect statistical analysis and visualizations. Before making any corrections, determine whether the dataset contains missing values.

Review the output and determine:

- Which columns contain missing values?
- How many missing values are present?

In [4]:
# Task 2.3: Explore Missing Values

# ENTER CODE BELOW THIS LINE.
dnkn.isnull().sum()

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

**Task 2.4:**

- Explore Number of Duplicate Records

- Duplicate records can distort analysis by counting the same observation multiple times.

How many duplicate records are present in the dataset?

In [5]:
# Task 2.4: Explore How Many Duplicate Records May Exist

# ENTER CODE BELOW THIS LINE.
dnkn.duplicated().sum()

np.int64(1)

**Task 2.5:**

- Explore the Nature of Duplicate Records

What are the duplicate records in the dataset? Should they be removed from the dataset?

In [6]:
# Task 2.5: Explore the Nature of Duplicate Records

# ENTER CODE BELOW THIS LINE.
dnkn[dnkn.duplicated]

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
760,Sandwiches,Ham and Cheese Rollups,280,13,6,0,40,1050,27,1,2,13,275

**Task 2.6:** Explore Unique Values

- Business analysts often review categorical variables to identify inconsistencies, misspellings, or unusual entries.

Show the unique counts for all variables. How would you interpret this output?

In [7]:
# Task 2.6: Explore Unique Values

# ENTER CODE BELOW THIS LINE.
dnkn.nunique()

Category                23
Item                   779
Calories                87
Total Fat (g)           50
Saturated Fat (g)       29
Trans Fat (g)            5
Cholesterol (mg)        37
Sodium (mg)            112
Carbs (g)              120
Fiber (g)                9
Sugars (g)             122
Protein (g)             32
Weight Watcher Pnts    362
dtype: int64

**Task 2.7:** 

- Examine the beverage categories.

Show the unique counts for all beverage categories. How would you interpret this output?

Are there any category labels that do not appear to be products?
Are there any inconsistent category names?
Are there unusual values?

In [8]:
# Task 2.7: Examine the Beverage Categories.

# ENTER CODE BELOW THIS LINE.
dnkn['Category'].value_counts()

Category
Hot Coffee            88
Donuts                87
Hot Latte             63
Iced Coffee           63
Iced Latte            63
Sandwiches            55
Frozen Coffee         49
Hot Macchiato         45
Hot Cappuccino        43
Iced Cappuccino       42
Iced Macchiato        42
Iced Tea              33
Hot Chocolate         28
Muffins               18
Kolache               16
Cold Brew Coffee      11
Coolatta               9
Dunkin’ Refreshers     9
Soft Serve             8
Hot Americano          3
Iced Americano         3
Hash Browns            1
Dunkin’ Bowls          1
Name: count, dtype: int64

**Task 2.8:**

- Explore Numerical Variables

The describe() function can be used to examine continuous variables and identify unusual values.

What are the:

- Minimum values
- Maximum values
- Means
- Missing values

In [9]:
# Task 2.8: Explore Numerical Variables

# ENTER CODE BELOW THIS LINE.
dnkn.describe(include='all')

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
count,780,780,780,780,780,780,780,780,780,780,780,780,780
unique,23,779,87,50,29,5,37,112,120,9,122,32,362
top,Hot Coffee,Ham and Cheese Rollups,170,0,0,0,0,180,35,0,0,4,5
freq,88,2,38,242,269,755,222,24,30,508,33,94,13

**Task 2.9:**

- Identify Special Characters in the Total Fat (g) Column

Sometimes data contains special values, such as "zero", "N/A", "*", "<", "=", etc. A "special value" is any value that prevents a column from behaving as expected. For example, "zero" is not the same thing as 0. You need to identify them in the data and treat them so that a numeric column just has numbers. There are various ways to do this. You can examine each column and look for these special characters. 

Identify special characters in the Total Fat (g), Saturated Fat (g), Trans Fat (g), Cholesterol (mg), Sodium (mg), Fiber (g), Protein (g), and Carbs (g).

In [12]:
# Task 2.9a: Identify Special Characters in the Total Fat (g) Column

# ENTER CODE BELOW THIS LINE.
print(list(dnkn['Total Fat (g)'].unique()))

['0', '12', '9', '6', '4.5', '3', '10', '11', '28', '30', '22', '21', '23', '14', '15', '20', '19', '16', '18', '25', '31', '27', '17', '37', '40', '5', '8', '35', '26', '13', '7', '\xa0', '4', '1', '0.5', '1.5', '2.5', '2', '3.5', '42', '33', '24', '36', '54', '29', '32', '34', '52', '41', '43']

In [14]:
# Task 2.9b: Identify Special Characters in the Saturated Fat (g) Column

# ENTER CODE BELOW THIS LINE.
print(list(dnkn['Saturated Fat (g)'].unique()))

['0', '6', '4.5', '3', '3.5', '2.5', '1.5', '4', '12', '14', '9', '10', '11', '7', '5', '8', '13', '18', '22', '17', '15', '\xa0', '0.5', '19', '21', '1', '2', '20', '16']

In [15]:
# Task 2.9c: Identify Special Characters in the Trans Fat (g) Column

# ENTER CODE BELOW THIS LINE.
print(list(dnkn['Trans Fat (g)'].unique()))

['0', '1.5', '1', '0.5', '\xa0']

In [16]:
# Task 2.9d: Identify Special Characters in the Cholesterol (mg) Column

# ENTER CODE BELOW THIS LINE.
print(list(dnkn['Cholesterol (mg)'].unique()))

['0', '35', '25', '20', '15', '10', '50', '30', '40', '130', '100', '70', '105', '80', '55', '<5', '\xa0', '125', '45', '60', '185', '340', '180', '95', '65', '190', '360', '195', '265', '175', '220', '120', '200', '240', '205', '110', '115']

In [17]:
# Task 2.9e: Identify Special Characters in the Sodium (mg) Column

# ENTER CODE BELOW THIS LINE.
print(list(dnkn['Sodium (mg)'].unique()))

['20', '15', '10', '65', '45', '30', '5', '60', '320', '240', '160', '300', '310', '470', '450', '420', '150', '340', '290', '400', '390', '440', '280', '135', '380', '480', '270', '430', '460', '360', '200', '370', '190', '330', '250', '170', '220', '180', '130', '230', '125', '100', '115', '75', '350', '260', '120', '\xa0', '95', '70', '50', '25', '85', '55', '90', '140', '105', '110', '210', '510', '570', '630', '500', '750', '620', '80', '40', '35', '1020', '810', '1260', '1460', '600', '410', '840', '1060', '800', '820', '1170', '520', '540', '670', '640', '1200', '590', '1190', '1210', '1080', '1240', '1980', '1010', '650', '960', '1140', '1220', '1270', '900', '910', '1050', '980', '1500', '1120', '710', '550', '850', '490', '760', '970', '580', '1160', '700', '680']

In [18]:
# Task 2.9f: Identify Special Characters in the Fiber (g) Column

# ENTER CODE BELOW THIS LINE.
print(list(dnkn['Fiber (g)'].unique()))

['0', '1', '2', '3', '4', '\xa0', '6', '5', '8']

In [19]:
# Task 2.9g: Identify Special Characters in the Protein (g) Column

# ENTER CODE BELOW THIS LINE.
print(list(dnkn['Protein (g)'].unique()))

['1', '0', '2', '10', '7', '5', '4', '6', '3', '8', '11', '9', '\xa0', '12', '16', '15', '14', '13', '27', '24', '37', '17', '19', '26', '21', '23', '18', '28', '33', '22', '25', '20']

In [20]:
# Task 2.9h: Identify Special Characters in the Carbs (g) Column

# ENTER CODE BELOW THIS LINE.
print(list(dnkn['Carbs (g)'].unique()))

['0', '2', '1', '37', '27', '18', '112', '84', '56', '172', '129', '86', '113', '85', '31', '44', '57', '47', '63', '39', '55', '48', '36', '58', '33', '41', '34', '50', '40', '21', '42', '61', '43', '32', '52', '38', '59', '35', '45', '30', '49', '24', '176', '135', '95', '175', '134', '94', '180', '139', '97', '184', '142', '99', '141', '138', '183', '117', '88', '177', '160', '120', '80', '\xa0', '191', '147', '103', '195', '150', '105', '111', '83', '110', '13', '10', '7', '65', '64', '73', '70', '53', '71', '51', '87', '72', '66', '89', '82', '12', '9', '6', '26', '67', '5', '4', '46', '3', '28', '19', '17', '25', '23', '16', '15', '79', '78', '60', '11', '20', '54', '14', '69', '22', '75', '77', '29', '74', '68', '8', '92']

In [21]:
# Task 2.9i: Identify Special Characters in the Sugars (g) Column

# ENTER CODE BELOW THIS LINE.
print(list(dnkn['Sugars (g)'].unique()))

['0', '2', '1', '36', '27', '18', '110', '83', '55', '167', '125', '107', '80', '53', '10', '22', '24', '21', '11', '34', '32', '26', '14', '33', '20', '13', '15', '19', '16', '28', '17', '23', '12', '25', '5', '29', '165', '126', '88', '162', '124', '87', '158', '121', '84', '172', '132', '92', '176', '135', '94', '175', '134', '169', '130', '91', '173', '133', '93', '108', '81', '54', '112', '56', '111', '159', '119', '151', '113', '75', '\xa0', '181', '139', '97', '185', '142', '99', '98', '109', '82', '9', '6', '47', '35', '46', '63', '31', '61', '30', '60', '45', '58', '43', '57', '38', '62', '50', '39', '70', '42', '71', '65', '69', '64', '51', '66', '40', '49', '37', '7', '3', '4', '59', '48', '74', '52', '68', '67', '78', '8', '44', '85']

**Alternate method to identify special values:**

Instead of identifying each column, we could use a loop to iterate over them and find special values.
We are not doing it for the project. However, here is the code should you want to run it in a separate code block:

```python
 for col in dnkn.columns:
     if dnkn[col].dtype == 'object':
         print('\n', col)
         print(dnkn[col].unique()[:50])
```

**Task 2.10:** 

- Create a Cleaned Dataframe

Create a new dataframe named dnkn1 that will contain all cleaning modifications.

In [22]:
# Task 2.10: Create a Cleaned Dataframe

# ENTER CODE BELOW THIS LINE.
dnkn1 = dnkn.copy()

**Task 2.11:** 

- Remove Food Items from the Category Rows

Examine the dataset and identify rows that appear to be food category labels rather than actual beverage products.

Remove these rows from the dataframe. Do this by creating a new list of food items and then remove them from the dataset.

In [23]:
# Task 2.11: Remove Food Items from the Category Rows

# ENTER CODE BELOW THIS LINE.

food_items = ['Muffins', 'Hash Browns', 'Coolatta', 'Sandwiches', 'Dunkin’ Bowls', 'Donuts', 'Kolache', 'Soft Serve']

dnkn2 = dnkn1[~dnkn1['Category'].isin(food_items)].copy()

**Task 2.12:** 

- Verify duplicate item is removed.

Earlier, you identified a food item, Ham and Cheese Rollups, as a duplicate. When you dropped the food items, the duplicate item should have been removed. You should verify that it no longer exists in the dataframe.

In [24]:
# Task 2.12: Verify duplicate item is removed.

# ENTER CODE BELOW THIS LINE.
dnkn2.duplicated().sum()

np.int64(0)

**Task 2.13:** 

- Remove the special values inside each column.

Special characters were identified in the Total Fat (g), Saturated Fat (g), Trans Fat (g), Cholesterol (mg), Sodium (mg), Fiber (g), and Protein (g) columns.

You should have identified the "<5" special value in the Cholesterol (mg) column and the "\xaO" in multiple columns. The "<5" is isolated to the Cholesterol (mg) column, so that special value can be removed by just removing it from that one column. For the "\xaO" special character, you could remove it one column at a time, but there is a more efficient way to do it. You can remove it from all the columns at once. This is probably the best way to do it, but it is not exactly beginner-level, so I am providing the solution for you. I highly recommend that you run this code through an AI program and prompt it to explain it to you in detail:

```python
for col in dnkn2.select_dtypes(include='object').columns:
    dnkn2[col] = (
        dnkn2[col]
        .str.replace('\xa0', '', regex=False)
        .str.strip()
    )
```

In [25]:
# Task 2.13a: Remove the special values inside the Cholesterol column.

# Remove the <5 value from the Cholesterol column

# ENTER CODE BELOW THIS LINE.
dnkn2['Cholesterol (mg)'] = (dnkn2['Cholesterol (mg)'].replace('<5', '5'))

In [28]:
# Task 2.13b: Remove the "\xaO" special character from all columns:

# ENTER THE CODE BELOW THIS LINE:

for col in dnkn2.select_dtypes(include='object').columns:
    dnkn2[col] = dnkn2[col].str.replace('\xa0', '', regex=False).str.strip()

C:\Users\USERAS\AppData\Local\Temp\ipykernel_30404\3434662904.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in dnkn2.select_dtypes(include='object').columns:

**Task 2.14:** 

- Validate removal of all special characters.

Normally, you would validate all columns. I am providing some code for you to validate the removal of all special values. Run the code and inspect the output.

```python
for col in dnkn.columns:
    if dnkn2[col].dtype == 'object':
        print('\n', col)
        print(dnkn2[col].unique()[:50])
```

In [32]:
# Task 2.14: Validate removal of all special characters.

# ENTER CODE BELOW THIS LINE.
for val in dnkn2.select_dtypes(include='object').columns:
    if val in ['Category', 'Item']:
        continue
    print(f"==={val}===")
    print(list(dnkn2[val].unique()))
    print("-"*40)

===Calories===
['5', '120', '90', '60', '260', '190', '130', '1120', '860', '610', '830', '650', '470', '880', '680', '490', '1110', '640', '460', '780', '590', '390', '500', '370', '250', '550', '410', '930', '710', '510', '790', '400', '', '1160', '890', '630', '720', '480', '360', '240', '530', '10', '70', '45', '230', '170', '110', '160', '80', '290', '220', '150', '310', '380', '280', '300', '270', '180', '540', '350', '570', '210', '580', '330', '420', '340', '35', '25', '15', '320', '30', '20', '200', '140', '50', '40', '440', '450', '520', '100', '430', '900', '700']
----------------------------------------
===Total Fat (g)===
['0', '12', '9', '6', '40', '31', '22', '5', '4.5', '11', '8', '35', '26', '17', '13', '14', '10', '7', '', '3', '4', '1', '0.5', '23', '21', '15', '16', '1.5', '2.5', '2', '18', '3.5']
----------------------------------------
===Saturated Fat (g)===
['0', '6', '4.5', '3', '22', '17', '12', '3.5', '7', '18', '14', '9', '2.5', '15', '10', '5', '', '1.5', '0.5', '4', '19', '8', '21', '13', '11', '1']
----------------------------------------
===Trans Fat (g)===
['0', '1.5', '1', '0.5', '']
----------------------------------------
===Cholesterol (mg)===
['0', '35', '25', '20', '130', '100', '70', '40', '30', '105', '80', '55', '5', '15', '10', '', '125', '50', '45', '60']
----------------------------------------
===Sodium (mg)===
['20', '15', '10', '65', '45', '30', '5', '290', '220', '160', '240', '180', '130', '280', '150', '230', '125', '200', '100', '115', '75', '350', '260', '120', '', '480', '370', '250', '430', '330', '95', '70', '50', '25', '85', '55', '60', '135', '90', '170', '140', '105', '110', '190', '210', '510', '470', '340', '570', '460', '390', '630', '500', '380', '440', '320', '750', '620', '450', '80', '40', '35', '270', '310', '420', '300']
----------------------------------------
===Carbs (g)===
['0', '2', '1', '37', '27', '18', '180', '139', '97', '184', '142', '99', '141', '138', '183', '113', '85', '57', '117', '88', '59', '177', '134', '94', '160', '120', '80', '', '191', '147', '103', '195', '150', '105', '111', '83', '55', '110', '13', '10', '7', '48', '36', '24', '65', '49', '33', '32', '64', '63', '47', '40', '73', '52', '86', '70', '53', '35', '71', '51', '87', '72', '66', '44', '89', '82', '12', '9', '6', '39', '26', '67', '38', '5', '4', '46', '3', '28', '19', '17', '42', '50', '25', '23', '16', '15', '61', '43', '79', '78', '60', '11', '20', '54', '41', '14', '69', '45', '34', '22', '75', '56', '77', '29', '21', '175', '95']
----------------------------------------
===Fiber (g)===
['0', '3', '2', '', '1', '4']
----------------------------------------
===Sugars (g)===
['0', '2', '1', '36', '27', '18', '172', '132', '92', '176', '135', '94', '175', '134', '169', '130', '91', '173', '133', '93', '108', '81', '54', '112', '84', '56', '111', '159', '119', '83', '151', '113', '75', '', '181', '139', '97', '185', '142', '99', '98', '109', '82', '12', '9', '6', '47', '35', '23', '46', '63', '32', '31', '61', '30', '60', '45', '58', '43', '29', '57', '53', '38', '26', '62', '50', '25', '55', '39', '70', '42', '88', '71', '65', '69', '64', '51', '66', '40', '49', '37', '24', '7', '5', '3', '4', '28', '19', '17', '34', '59', '16', '14', '48', '74', '52', '68', '67', '33', '20', '15', '10', '13', '22', '21', '78', '162', '124', '87']
----------------------------------------
===Protein (g)===
['1', '0', '2', '10', '8', '6', '11', '9', '7', '5', '3', '4', '', '12', '16', '15', '14', '13']
----------------------------------------
===Weight Watcher Pnts===
['4', '5', '126', '93.5', '63', '300', '219.5', '150', '1304', '1001', '708', '998.5', '779', '561', '1051', '812', '582.5', '1291', '999', '707', '995.5', '767', '550', '1049', '810', '580.5', '899', '680', '450', '604', '448', '302', '657.5', '491.5', '1094', '833', '597', '942', '703', '476', '', '1352', '1038', '733', '1056.5', '816', '586', '1111', '859', '606.5', '581', '436', '290', '634.5', '467.5', '311.5', '10', '94', '73', '47', '269', '199', '129', '168.5', '126.5', '84.5', '332.5', '252.5', '171.5', '362', '186', '436.5', '322.5', '218.5', '360', '268', '175', '424.5', '320.5', '217.5', '348.5', '256.5', '174', '413', '310', '206.5', '359', '266', '423.5', '256', '613', '556', '397', '272', '649', '534', '399', '261', '463', '325', '220', '571', '466', '349', '244', '671', '532', '405', '382', '589', '486', '358', '243', '93', '72', '158.5', '116.5', '340', '278', '205', '134', '488', '394', '300.5', '196', '132', '485', '391', '288.5', '337', '51', '39', '27', '17', '157', '371', '31', '25', '20', '16', '195', '146', '98', '212', '135', '87', '52.5', '42', '20.5', '265.5', '231', '108.5', '314.5', '254', '192', '472', '380', '277', '185.5', '381', '280', '190.5', '95.5', '74', '264', '203', '483', '287.5', '502.5', '388', '285', '599', '464', '404', '301', '207', '512', '386', '260.5', '478', '375.5', '282.5', '585', '451', '336', '402', '299', '509', '374', '249.5', '384', '148', '114', '79', '136', '105', '311', '179', '417', '305', '203.5', '390.5', '497', '373', '248.5', '400', '298', '508', '201', '377', '187.5', '279', '185', '434.5', '52', '139', '266.5', '423', '320', '184', '433.5', '216.5', '41', '216', '492.5', '374.5', '281.5', '161', '124', '85', '173', '125', '86', '183', '97', '15', '288', '189', '411', '210', '218', '158', '110', '206', '156', '1063', '825']
----------------------------------------

C:\Users\USERAS\AppData\Local\Temp\ipykernel_30404\2018976147.py:4: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for val in dnkn2.select_dtypes(include='object').columns:

**Task 2.15:**

- Remove '' empty strings and replace with NaN values.

Now that you removed the special values from the dnkn2 dataframe, the removal of them created a '' entry in your columns. This is an empty string. These must be treated. Although the special character is gone, the empty string still represents missing information. Therefore, the empty string must be converted to a NaN value so Python can properly identify and manage missing data.

The process is to convert the '' to an NaN. You need to import numpy as np and replace the '' entries in the dnkn2 dataframe with nan values.

dnkn2 = dnkn2.replace('', np.nan)

In [33]:
# Task 2.15: Remove '' empty strings and replace with NaN values.

# ENTER CODE BELOW THIS LINE.
import numpy as np

dnkn2 = dnkn2.replace('', np.nan)

**Task 2.16:**

- Validate conversion of '' empty strings with NaN values.

We need to validate that the empty strings created by the removal of the '\xa0' special value have been converted to NaN values.

In [34]:
# Task 2.16: Validate conversion of '' empty strings with NaN values.

# ENTER CODE BELOW THIS LINE.
dnkn2.isnull().sum()

Category               0
Item                   0
Calories               3
Total Fat (g)          3
Saturated Fat (g)      3
Trans Fat (g)          3
Cholesterol (mg)       3
Sodium (mg)            3
Carbs (g)              3
Fiber (g)              3
Sugars (g)             3
Protein (g)            3
Weight Watcher Pnts    3
dtype: int64

**Task 2.17:**

- Create a new dnkn3 object and drop the NaN values from the dataframe.
    
Creation of the dnkn3 object is a good practice so the Python code does not get earlier dataframe versions mixed up.

In [36]:
# Task 2.17: Create a new dnkn3 object and drop the NaN values from the dataframe.

# ENTER CODE BELOW THIS LINE.
dnkn3 = dnkn2.dropna().copy()

**Task 2.18:**

- Validate removal of the NaN values from the dataframe.

In [37]:
# Task 2.18: Validate removal of the NaN values from the dataframe.

# ENTER CODE BELOW THIS LINE.
dnkn3.isnull().sum()

Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

**Task 2.19:** 

Convert Data Types

- Convert all numerical data types originally classified as objects.

Convert the variables to numeric data types. Create a new object called "numeric_columns" and create a list of all variables that are supposed to be classified as numeric. Then, us the following code to convert them:

```python
for col in numeric_columns:
    dnkn3[col] = pd.to_numeric(dnkn3[col])
```

In [38]:
# Task 2.19: Convert Data Types

# ENTER CODE BELOW THIS LINE.
# Create an object called "numeric_columns" and list all columns.
numeric_columns = ['Calories', 'Total Fat (g)', 'Saturated Fat (g)', 'Trans Fat (g)', 'Cholesterol (mg)', 'Sodium (mg)', 'Carbs (g)', 'Fiber (g)', 'Sugars (g)', 'Protein (g)', 'Weight Watcher Pnts']


# Convert list of "numeric_columns" to numeric data types 
for convert in numeric_columns:
    if convert in dnkn3.columns:
        dnkn3[convert] = pd.to_numeric(dnkn3[convert])

**Task 2.20:**

- Summary Validations

It is a good practice to validate all items that have been cleaned up. We can summarize these with clean and neat print outs. Run the code below and if you addressed all the items properly, you will have no missing values, all numeric data types have been converted to either int64 or float64, all categories just contain beverage items, there are no special values, the datashape is (599, 13), and there are no summary statistics that are unreasonable.

In [39]:
# Task 2.20: Summary Validations

# To remove the hashtags (#), just highlight the following code with the word "print" in front it of, then hit control + forward slash /. 
# Then run the code for this block.

print("========== MISSING VALUES ==========")
print(dnkn3.isnull().sum())

print("\n========== DATA TYPES ==========")
print(dnkn3.dtypes)

print("\n========== DUPLICATE RECORDS ==========")
print("Duplicates:", dnkn3.duplicated().sum())

print("\n========== CATEGORY CHECK ==========")
print(dnkn3['Category'].value_counts())

print("\n========== SPECIAL VALUE CHECK ==========")
print("Cholesterol Values:")
print(dnkn3['Cholesterol (mg)'].unique())

print("\nTotal Fat Values:")
print(dnkn3['Total Fat (g)'].unique())

print("\n========== DATASET SHAPE ==========")
print(dnkn3.shape)

print("\n========== SUMMARY STATISTICS ==========")
print(dnkn3.describe().round(2))

========== MISSING VALUES ==========
Category               0
Item                   0
Calories               0
Total Fat (g)          0
Saturated Fat (g)      0
Trans Fat (g)          0
Cholesterol (mg)       0
Sodium (mg)            0
Carbs (g)              0
Fiber (g)              0
Sugars (g)             0
Protein (g)            0
Weight Watcher Pnts    0
dtype: int64

========== DATA TYPES ==========
Category                   str
Item                       str
Calories                 int64
Total Fat (g)          float64
Saturated Fat (g)      float64
Trans Fat (g)          float64
Cholesterol (mg)         int64
Sodium (mg)              int64
Carbs (g)                int64
Fiber (g)                int64
Sugars (g)               int64
Protein (g)              int64
Weight Watcher Pnts    float64
dtype: object

========== DUPLICATE RECORDS ==========
Duplicates: 0

========== CATEGORY CHECK ==========
Category
Hot Coffee            88
Hot Latte             63
Iced Coffee           63
Iced Latte            63
Frozen Coffee         47
Hot Macchiato         45
Hot Cappuccino        42
Iced Cappuccino       42
Iced Macchiato        42
Iced Tea              33
Hot Chocolate         28
Cold Brew Coffee      11
Dunkin’ Refreshers     9
Hot Americano          3
Iced Americano         3
Name: count, dtype: int64

========== SPECIAL VALUE CHECK ==========
Cholesterol Values:
[  0  35  25  20 130 100  70  40  30 105  80  55   5  15  10 125  50  45
  60]

Total Fat Values:
[ 0.  12.   9.   6.  40.  31.  22.   5.   4.5 11.   8.  35.  26.  17.
 13.  14.  10.   7.   3.   4.   1.   0.5 23.  21.  15.  16.   1.5  2.5
  2.  18.   3.5]

========== DATASET SHAPE ==========
(582, 13)

========== SUMMARY STATISTICS ==========
       Calories  Total Fat (g)  Saturated Fat (g)  Trans Fat (g)  \
count    582.00         582.00             582.00         582.00
mean     247.74           4.92               2.96           0.02
std      181.34           6.24               3.90           0.15
min        5.00           0.00               0.00           0.00
25%      130.00           0.00               0.00           0.00
50%      220.00           4.00               2.50           0.00
75%      330.00           8.00               4.50           0.00
max     1160.00          40.00              22.00           1.50

       Cholesterol (mg)  Sodium (mg)  Carbs (g)  Fiber (g)  Sugars (g)  \
count            582.00       582.00     582.00     582.00      582.00
mean              14.97       138.27      44.96       0.33       41.76
std               17.90       110.99      34.61       0.73       32.43
min                0.00         5.00       0.00       0.00        0.00
25%                0.00        60.00      25.00       0.00       23.00
50%               10.00       115.00      39.00       0.00       37.00
75%               25.00       180.00      61.00       0.00       54.75
max              130.00       750.00     195.00       4.00      185.00

       Protein (g)  Weight Watcher Pnts
count       582.00               582.00
mean          5.94               286.53
std           4.04               213.06
min           0.00                 4.00
25%           2.00               150.00
50%           6.00               256.50
75%           9.00               377.00
max          16.00              1352.00

**Task 2.21:**

- Save the dnkn3 Python file to a CSV file.

In [40]:
# Task 2.21: Save the dnkn3 Python file to a CSV file.

# ENTER CODE BELOW THIS LINE.
dnkn3.to_csv('dnkn_clean.csv',index=False)

**Task 2.22:**

- Reload the dnkn3 Python CSV file and save it as a new object, dnkn4.

In [42]:
# Task 2.22: Reload the dnkn3 Python CSV file and save it as a new object, dnkn4. Validate it.

# ENTER CODE BELOW THIS LINE.
dnkn4 = pd.read_csv('dnkn_clean.csv')

# To validate, check first 5 rows of data.
dnkn4.head()

,Category,Item,Calories,Total Fat (g),Saturated Fat (g),Trans Fat (g),Cholesterol (mg),Sodium (mg),Carbs (g),Fiber (g),Sugars (g),Protein (g),Weight Watcher Pnts
0,Cold Brew Coffee,"Cold Brew Coffee, Large",5,0.0,0.0,0.0,0,20,0,0,0,1,4.0
1,Cold Brew Coffee,"Cold Brew Coffee, Medium",5,0.0,0.0,0.0,0,15,0,0,0,0,5.0
2,Cold Brew Coffee,"Cold Brew Coffee, Small",5,0.0,0.0,0.0,0,10,0,0,0,0,5.0
3,Cold Brew Coffee,"Cold Brew Coffee with Cream, Large",120,12.0,6.0,0.0,35,65,2,0,2,2,126.0
4,Cold Brew Coffee,"Cold Brew Coffee with Cream, Medium",90,9.0,4.5,0.0,25,45,1,0,1,2,93.5

**Task 2.23:**

Summarize the issues with the Dunkin' Donuts dataset.

In a two or three-paragraph layman's summary, tell your client what you did for Deliverable Two.

ENTER YOUR SUMMARY HERE:

In [ ]:
#About Dunkin Donut datast, Cleaning data was the main focus and there were some issues to resolved to make it done. The issues are identified as, 
#having special charecters and empty cells, and 
#having food items rather then only beverage.

In [ ]:
# I have remove all the empty cells and special charecters then organised it in a meaningful way by removing everything else than beverage.